# Copyright 2018 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Full example of a Fleet resource - a set of warm GameServers
# that are available to be allocated from.
# To allocate a GameServer from a Fleet, use a FleetAllocation
#

apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
metadata:
  # Fleet Metadata
  # https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#objectmeta-v1-meta
  name: fleet-example
spec:
  # the number of GameServers to keep Ready or Allocated in this Fleet
  replicas: 2
  # a GameServer template - see:
  # https://github.com/GoogleCloudPlatform/agones/blob/master/docs/gameserver_spec.md for all the options
  strategy:
    # The replacement strategy for when the GameServer template is changed. Current option is "Recreate",
    # "RollingUpdate" will come at a later date.
    # "Recreate" terminates all non-allocated GameServers, and starts up a new set with the new details to replace them.
    type: Recreate
  template:
    # GameServer metadata
    metadata:
      labels:
        foo: bar
    # GameServer specification
    spec:
      portPolicy: "dynamic"
      containerPort: 26000
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      # The GameServer's Pod template
      template:
        spec:
          containers:
          - name: example-server
            image: gcr.io/agones/test-server:0.1